[supervisord]
nodaemon=true
user=root

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=4
redirect_stderr=true
stopwaitsecs=3600
startsecs = 0

[program:cron]
user=root
command=cron -f
autostart=true
autorestart=true
stderr_logfile=/var/log/cron.err.log
stdout_logfile=/var/log/cron.out.log
startsecs = 0

[program:php]
command = docker-php-entrypoint php-fpm
